### ISSUE TITLE
Remove true-false from rule result

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/rule-901#23]
## Background

The impact of rule “Result”: false/true on the typology processing is artificial and the specific “subRuleRef” is already sufficiently unique to determine the weighting in the typology processor. https://github.com/frmscoe/General-Issues/issues/351

## User Story Statement

**As a** Tazama system operator
**I want** to remove the true and false rule outcomes; and
**I want** to replace the true/false weighting attributes with a weighting attribute
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

## Acceptance Criteria
1. Bump the FRMS-coe-lib version
2. Bump the FRMS-coe-startup-lib
2. Remove the `result` from the rule result for exit conditions in the rule processor

**Comment by Sandy-at-Tazama** [comment]
I found `outcome` in rule-901 tests [rule-901](https://github.com/frmscoe/rule-901/tree/dev)/[__tests__](https://github.com/frmscoe/rule-901/tree/dev/__tests__)/[unit](https://github.com/frmscoe/rule-901/tree/dev/__tests__/unit)
/rule.test.ts
@Justus-at-Tazama Do rule tests also need to be updated?

**Comment by rtkay123** [comment]
> I found `outcome` in rule-901 tests [rule-901](https://github.com/frmscoe/rule-901/tree/dev)/[**tests**](https://github.com/frmscoe/rule-901/tree/dev/__tests__)/[unit](https://github.com/frmscoe/rule-901/tree/dev/__tests__/unit) /rule.test.ts @Justus-at-Tazama Do rule tests also need to be updated?

They should.
Husky should have alerted. Fixing that...

**Comment by rtkay123** [comment]
Husky is not configured for this project https://github.com/frmscoe/rule-901/issues/24

Tests should be green now :)
